

package com.osucad.nameof.compiler.plugin.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.osucad.nameof.compiler.plugin.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class JvmBoxTestGenerated extends AbstractJvmBoxTest {
  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
  }

  @Test
  @TestMetadata("class-property-reference.kt")
  public void testClass_property_reference() {
    runTest("compiler-plugin/testData/box/class-property-reference.kt");
  }

  @Test
  @TestMetadata("field-access.kt")
  public void testField_access() {
    runTest("compiler-plugin/testData/box/field-access.kt");
  }

  @Test
  @TestMetadata("local-variable.kt")
  public void testLocal_variable() {
    runTest("compiler-plugin/testData/box/local-variable.kt");
  }

  @Test
  @TestMetadata("lorem-ipsum.kt")
  public void testLorem_ipsum() {
    runTest("compiler-plugin/testData/box/lorem-ipsum.kt");
  }

  @Test
  @TestMetadata("nameof-nullable-type.kt")
  public void testNameof_nullable_type() {
    runTest("compiler-plugin/testData/box/nameof-nullable-type.kt");
  }

  @Test
  @TestMetadata("nameof-type.kt")
  public void testNameof_type() {
    runTest("compiler-plugin/testData/box/nameof-type.kt");
  }

  @Test
  @TestMetadata("property-reference.kt")
  public void testProperty_reference() {
    runTest("compiler-plugin/testData/box/property-reference.kt");
  }
}
