

package com.osucad.nameof.compiler.plugin.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.osucad.nameof.compiler.plugin.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class JvmDiagnosticTestGenerated extends AbstractJvmDiagnosticTest {
  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
  }

  @Test
  @TestMetadata("array-access.kt")
  public void testArray_access() {
    runTest("compiler-plugin/testData/diagnostics/array-access.kt");
  }

  @Test
  @TestMetadata("constant.kt")
  public void testConstant() {
    runTest("compiler-plugin/testData/diagnostics/constant.kt");
  }

  @Test
  @TestMetadata("function-call.kt")
  public void testFunction_call() {
    runTest("compiler-plugin/testData/diagnostics/function-call.kt");
  }
}
